build.gradle, src/main/java/com/excella/reactor/ReactorApplication.java, src/main/java/com/excella/reactor/domain/Address.java, src/main/java/com/excella/reactor/domain/Bio.java, src/main/java/com/excella/reactor/domain/Contact.java, src/main/java/com/excella/reactor/domain/DomainModel.java, src/main/java/com/excella/reactor/domain/Employee.java, src/test/java/com/excella/reactor/ReactorApplicationTests.java, src/test/java/com/excella/reactor/controllers/EmployeeControllerUnitTests.java, start
-  Ran the linter, `./start goJF`, and formatted the files so the app compiles.
-  Small cleanup to `build.gradle`.
=> Fix formatting

README.md, build.gradle, test
-  Adds jacoco test coverage and test coverage report
-  Minimum is set to 0%, will bump up as more tests are added.
=> Jacoco test coverage

src/main/java/com/excella/reactor/controllers/SkillCategoryController.java, src/main/java/com/excella/reactor/domain/Skill.java, src/main/java/com/excella/reactor/domain/SkillCategory.java, src/main/java/com/excella/reactor/repositories/SkillCategoryRepository.java, src/main/java/com/excella/reactor/service/SkillCategoryService.java, src/main/java/com/excella/reactor/service/impl/SkillCategoryServiceImpl.java, src/main/resources/db/migration/V2__CreateSkillTables.sql
NOTE: This merge will require the postgres volume to be recreated if migrations have been run.
=> JA.17 Separate the Skill Category into its own Entity

src/test/java/com/excella/reactor/controllers/CrudControllerUnitTests.java, src/test/java/com/excella/reactor/service/CrudServiceUnitTests.java, src/test/java/com/excella/reactor/shared/SampleEntity.java
=> CrudService unit tests

Jenkinsfile, README.md, build.gradle, docker-compose.yml, src/main/java/com/excella/reactor/common/exceptions/CustomSetupException.java, src/main/java/com/excella/reactor/config/AuthorizationConfig.java, src/main/java/com/excella/reactor/config/CorsFilter.java, src/main/java/com/excella/reactor/config/ResourceConfig.java, src/main/java/com/excella/reactor/config/SecurityProperties.java, src/main/java/com/excella/reactor/config/SwaggerConfig.java, src/main/java/com/excella/reactor/config/WebSecurityConfiguration.java, src/main/resources/application.yml, src/main/resources/db/migration/V3__OAuthTables.sql, src/main/resources/db/migration/V4__UserTables.sql, src/main/resources/db/migration/V5__TEMPInsertClientUserDetails.sql, start
Please pull this down and try before approving. There are environment variables that need to be set and a JKS file that needs to be generated. Just need to make sure instructions are thorough enough to setup correctly.
=> JA-9 JA-10: OAuth2 and JWT Authorization and Authentication

start
=> Update start script

src/main/resources/db/migration/V6__SampleData.sql
Adds 20+ skills in 5 categories and 15 or so employees.  Enough to allow realistic paging, sorting and filtering examples.
=> Ja25 - Add default dummy data

README.md
=> Updating README with more links to tech challenge stuff.

src/main/java/com/excella/reactor/domain/Contact.java, src/test/java/com/excella/reactor/validation/ContactValidationTests.java, src/test/java/com/excella/reactor/validation/EmployeeValidationTests.java
Updating to use the regex for `(xxx)xxx-xxxx` for now, until we can use a real input mask on the front-end and then we can swap this back to just looking for 10 digits.
Related to Ja.12
=> Update email validation

.gitignore
Adding to .gitignore:
- dotenv file
- signing key
=> JA42 gitignore

src/inttest/java/com/excella/reactor/controllers/EmployeeEndpointTest.java, src/main/java/com/excella/reactor/config/AuthorizationConfig.java, src/main/java/com/excella/reactor/config/WebSecurityConfiguration.java, src/main/java/com/excella/reactor/domain/Contact.java, src/main/java/com/excella/reactor/domain/Employee.java, src/main/java/com/excella/reactor/domain/User.java, src/main/java/com/excella/reactor/domain/UserAuthority.java, src/main/java/com/excella/reactor/repositories/UserRepository.java, src/main/java/com/excella/reactor/service/impl/UserDetailsServiceImpl.java, src/main/resources/db/migration/V4__UserTables.sql, src/main/resources/db/migration/V5__TEMPInsertClientUserDetails.sql, src/test/java/com/excella/reactor/controllers/EmployeeControllerUnitTests.java, src/test/java/com/excella/reactor/controllers/SkillCategoryControllerUnitTests.java, src/test/java/com/excella/reactor/controllers/SkillControllerUnitTests.java, src/test/java/com/excella/reactor/service/impl/EmployeeServiceImplUnitTests.java, src/test/java/com/excella/reactor/service/impl/SkillCategoryServiceImplUnitTests.java, src/test/java/com/excella/reactor/service/impl/SkillServiceImplUnitTests.java, src/test/java/com/excella/reactor/service/impl/UserDetailsServiceImplUnitTests.java
Please remove Postgres volume before trying this out. Migrations have been edited.
=> JA-25: Adding Email to User

src/inttest/java/com/excella/reactor/controllers/EmployeeEndpointTest.java, src/main/java/com/excella/reactor/domain/Contact.java, src/test/java/com/excella/reactor/controllers/EmployeeControllerUnitTests.java, src/test/java/com/excella/reactor/controllers/SkillCategoryControllerUnitTests.java, src/test/java/com/excella/reactor/controllers/SkillControllerUnitTests.java, src/test/java/com/excella/reactor/service/impl/EmployeeServiceImplUnitTests.java, src/test/java/com/excella/reactor/service/impl/SkillCategoryServiceImplUnitTests.java, src/test/java/com/excella/reactor/service/impl/SkillServiceImplUnitTests.java
I was testing the app and the build task failed because of google-java-format issues, so I ran it and it gave these updates.
=> Ran goJF to make it happy

README.md, README.md.xg, generate-keystore, get-token
This PR does three things:
1) Automate generating the Java KeyStore (JKS) and the corresponding .env file
2) Automate getting an OAuth token from the API
3) Update the documentation to: cover (1) and (2), while leaving the manual steps as an alternative; fix a couple ordering problems with the steps; fix some typos and out-of-date information in the steps.
=> Documentation enhancement

src/main/resources/db/migration/V5__TEMPInsertClientUserDetails.sql
Fix a broken migration failing the integration pipeline and breaking bootrun
=> Fix integration tests

src/main/java/com/excella/reactor/config/WebSecurityConfiguration.java
=> Remove extra blank line.

README.md
=> Adds build badge from jenkins.

README.md
- Adds code coverage and vulnerabilities badges from sonarqube
=> Add badges from sonarqube.

README.md
Updated the badges links (to make @vickumar1981  happy)
=> Updated links for badges

.gitignore, Jenkinsfile, tcp-java-ecs/deploy-to-ecs, tcp-java-ecs/docker-compose.yml, tcp-java-ecs/package-for-ecs
Note that the docker-compose.yml file this changes is the ECS one, which is separate from the normal one.
Also, this will not work until a parallel PR to tcp-ecs is merged.
Finally, the Jenkins instance needs to set an AWS_REGION global environment variable.
=> Use RDS for db host

Jenkinsfile-ocp
Massively simplified - Let's see if we can mix and match Gradle commands with the S2I build config.
=> First attempt at Openshift Jenkinsfile

src/main/java/com/excella/reactor/controllers/CrudController.java, src/test/java/com/excella/reactor/controllers/CrudControllerUnitTests.java
- Fixes paging issue with Webflux and `Pageable`. 
@ephultman @gpacix
=> Fix paging issue with Pageable and Webflux.
